sudo: required

language: bash

install:
  - sudo apt-get update -qqy
  - sudo apt-get install -y jq

before_script:
  - chmod +x ./please
  - bash -n ./please

script:
  - 'export COMMITS=$(git log -50 --oneline --pretty="%s" --no-merges --grep "skip" --grep "Revert" --invert-grep ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --)'
  - 'export FILTERED=$(echo -e "$COMMITS" | grep -E "^(build|docs|chore|feat|fix|infra|perf|rebase|refactor|release|revert|style|test)(\(\w+\))?: [a-z].+")'
  - 'echo -e "$COMMITS" > .commits && echo -e "$FILTERED" > .filtered'
  - '[ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && diff .commits .filtered'

after_success:
  - '[ "${TRAVIS_BRANCH}" == "master" ] && ./please --vfile --chlog --chash --yes'
